const notFoundError = (res) => {
    return res.status(404).send("A tarefa n√£o foi localizada no banco!");
};

module.exports = {
    notFoundError,
};
